-- insert into customers(first_name, last_name)
-- 	values('Greg', 'Jones'),
-- 		('Sandra', 'Jones'),
-- 		('Scott', 'Scott'),
-- 		('Trevor', 'Green'),
-- 		('Melanie', 'Johnson'
-- 	)
-- select * from items;
-- select * from items where price > 80;
-- select * from items where price < 300;
-- select * from customers where last_name='Smith';
-- select * from customers where last_name='Jones';
select * from customers where first_name!='Scott';
